# Generated by Django 2.2 on 2019-04-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20190426_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
