# Generated by Django 2.2 on 2019-04-27 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_case_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='published_date',
        ),
    ]
